name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added?
