name: Docs check
on:
  push:
  pull_request:
jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose .
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdownlint
        uses: avto-dev/markdown-lint@v1
        with:
          config: '{"default": true}'
